# Generated by Django 5.0.4 on 2024-04-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='subtotal',
        ),
    ]
