# Generated by Django 5.0.4 on 2024-04-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_remove_purchase_correlative_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.AlterModelTable(
            name='purchase',
            table=None,
        ),
    ]
