# Generated by Django 5.0.4 on 2024-04-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_purchase_options_alter_purchase_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'purchase', 'verbose_name_plural': 'purchases'},
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='Purchases',
        ),
    ]
