# Generated by Django 5.0.4 on 2024-04-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_purchase_options_alter_purchase_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_type',
        ),
    ]
