# Generated by Django 5.0.4 on 2024-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_remove_purchase_purchase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('finished', 'Finished'), ('pending', 'Pending')], default='finished', max_length=120),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of product'),
        ),
    ]
