# Generated by Django 5.0.4 on 2024-04-26 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_supplier_description_supplier_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the customer's full name", max_length=255, verbose_name='Customer Name')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Enter customer email', max_length=254, null=True, unique=True, verbose_name='Email')),
                ('address', models.TextField(help_text="Enter the customer's address", verbose_name='Address')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative_number', models.CharField(db_index=True, max_length=20, null=True, unique=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Sale date')),
                ('state', models.CharField(choices=[('canceled', 'Canceled'), ('finished', 'Finished')], default='finished', max_length=120)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(help_text='Customer associated with the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'db_table': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, help_text='Number of products sold', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price of the product on sale', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal', max_digits=10)),
                ('product', models.ForeignKey(help_text='Product sold', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(help_text='Sale to which the item belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'sale item',
                'verbose_name_plural': 'sale items',
                'db_table': 'SaleItems',
            },
        ),
    ]
