# Generated by Django 5.0.4 on 2024-04-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_shipping_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='correlative_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sale price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('finished', 'Finished'), ('pending', 'Pending')], default='finished', max_length=120),
        ),
    ]
