# Generated by Django 5.0.4 on 2024-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_correlative_number_remove_sale_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, help_text='Number of products sold', null=True),
        ),
    ]
