# Generated by Django 5.0.4 on 2024-04-26 06:57

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('level', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Product name', max_length=100)),
                ('description', models.TextField(help_text='Product description')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Product purchase price', max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Product sale price', max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, help_text='Product offer price', max_digits=10)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.ForeignKey(help_text='Product Category', on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.category')),
                ('supplier', models.ForeignKey(help_text='Product supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.supplier')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'Products',
                'ordering': ['name', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('size', 'Size'), ('color', 'Color')], default='size', max_length=120)),
                ('name', models.CharField(help_text='Variation name', max_length=120)),
                ('state', models.BooleanField(choices=[('available', 'Available'), ('not available', 'Not available'), ('deleted', 'Deleted')], default='available', max_length=120)),
                ('stock', models.PositiveIntegerField(default=1, help_text='Available stock of the product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attrs', to='products.product')),
            ],
            options={
                'db_table': 'Variations',
            },
        ),
    ]
