# Generated by Django 5.0.4 on 2024-04-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='state',
            field=models.CharField(choices=[('available', 'Available'), ('not available', 'Not available'), ('deleted', 'Deleted')], default='available', max_length=120),
        ),
    ]
