# Generated by Django 5.0.4 on 2024-04-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_level_alter_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the supplier', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, help_text='Image representing the supplier', null=True, upload_to='suppliers/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(blank=True, help_text='Type of supplier (e.g., wholesaler, retailer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='url',
            field=models.URLField(blank=True, help_text="URL of the supplier's online store", null=True),
        ),
    ]
