# Generated by Django 5.0.4 on 2024-04-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Product purchase price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(help_text='Product supplier', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.supplier'),
        ),
    ]
