# Generated by Django 5.0.4 on 2024-04-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_variation_stock_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Product sale price', max_digits=10),
        ),
    ]
