# Generated by Django 5.0.4 on 2024-04-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_slug_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock',
            field=models.PositiveIntegerField(default=0, help_text='Maximum stock of the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, help_text='Minimum stock of the product'),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
