# Generated by Django 5.0.4 on 2024-04-30 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_max_stock_product_min_stock_delete_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Available stock of the product')),
                ('min_stock', models.PositiveIntegerField(default=0, help_text='Minimum stock of the product')),
                ('max_stock', models.PositiveIntegerField(default=0, help_text='Maximum stock of the product')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventories',
                'db_table': 'Inventories',
            },
        ),
    ]
