# Generated by Django 5.0.4 on 2024-05-01 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_max_stock_remove_product_min_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('default', 'Default'), ('imperfect', 'Imperfect'), ('damaged', 'Damaged')], default='default', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional details about the issue', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='products.product')),
            ],
            options={
                'verbose_name': 'product issue',
                'verbose_name_plural': 'product issues',
                'db_table': 'ProductIssues',
            },
        ),
    ]
